# 1. 베이스 이미지 지정
FROM alpine:3.24.1

# 2. 이미지 메타데이터 명세
LABEL maintainer="kilyong <kilyong@example.com>"
LABEL version="1.0.0"
LABEL environment="production"
LABEL description="Spring Board Nginx Web Server Image"

# 3. 내부 작업 디렉터리 생성/이동
WORKDIR /app